// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AddTagToPostData, AddTagToPostErrors, AddTagToPostResponses, CreateCategoryData, CreateCategoryErrors, CreateCategoryResponses, CreatePostData, CreatePostErrors, CreatePostResponses, CreateTagData, CreateTagErrors, CreateTagResponses, DeleteCategoryData, DeleteCategoryErrors, DeleteCategoryResponses, DeletePostData, DeletePostErrors, DeletePostResponses, DeleteTagData, DeleteTagErrors, DeleteTagResponses, GetActivityData, GetActivityErrors, GetActivityResponses, GetCategoriesData, GetCategoriesErrors, GetCategoriesResponses, GetCategoryBySlugData, GetCategoryBySlugErrors, GetCategoryBySlugResponses, GetHealthData, GetHealthResponses, GetMeData, GetMeErrors, GetMeResponses, GetMyStatsData, GetMyStatsErrors, GetMyStatsResponses, GetPostBySlugData, GetPostBySlugErrors, GetPostBySlugResponses, GetPostsData, GetPostsResponses, GetPublicUserByIdData, GetPublicUserByIdErrors, GetPublicUserByIdResponses, GetTagBySlugData, GetTagBySlugErrors, GetTagBySlugResponses, GetTagsData, GetTagsResponses, LoginData, LoginErrors, LoginResponses, RegisterData, RegisterErrors, RegisterResponses, RemoveTagFromPostData, RemoveTagFromPostErrors, RemoveTagFromPostResponses, UpdateCategoryData, UpdateCategoryErrors, UpdateCategoryResponses, UpdateMeData, UpdateMeErrors, UpdateMePasswordData, UpdateMePasswordErrors, UpdateMePasswordResponses, UpdateMeResponses, UpdatePostBySlugData, UpdatePostBySlugErrors, UpdatePostBySlugResponses, UpdateTagData, UpdateTagErrors, UpdateTagResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Register a new user
 */
export const register = <ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>) => (options.client ?? client).post<RegisterResponses, RegisterErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Login with email and password
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get posts paginated
 */
export const getPosts = <ThrowOnError extends boolean = false>(options?: Options<GetPostsData, ThrowOnError>) => (options?.client ?? client).get<GetPostsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/posts/',
    ...options
});

/**
 * Create a new post
 */
export const createPost = <ThrowOnError extends boolean = false>(options: Options<CreatePostData, ThrowOnError>) => (options.client ?? client).post<CreatePostResponses, CreatePostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/posts/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a post
 */
export const deletePost = <ThrowOnError extends boolean = false>(options: Options<DeletePostData, ThrowOnError>) => (options.client ?? client).delete<DeletePostResponses, DeletePostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/posts/slug/{slug}',
    ...options
});

/**
 * Get post by slug
 */
export const getPostBySlug = <ThrowOnError extends boolean = false>(options: Options<GetPostBySlugData, ThrowOnError>) => (options.client ?? client).get<GetPostBySlugResponses, GetPostBySlugErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/posts/slug/{slug}',
    ...options
});

/**
 * Update a post
 */
export const updatePostBySlug = <ThrowOnError extends boolean = false>(options: Options<UpdatePostBySlugData, ThrowOnError>) => (options.client ?? client).patch<UpdatePostBySlugResponses, UpdatePostBySlugErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/posts/slug/{slug}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Remove a tag from a post
 */
export const removeTagFromPost = <ThrowOnError extends boolean = false>(options: Options<RemoveTagFromPostData, ThrowOnError>) => (options.client ?? client).delete<RemoveTagFromPostResponses, RemoveTagFromPostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/posts/slug/{slug}/tags/{tagSlug}',
    ...options
});

/**
 * Add a tag to a post
 */
export const addTagToPost = <ThrowOnError extends boolean = false>(options: Options<AddTagToPostData, ThrowOnError>) => (options.client ?? client).put<AddTagToPostResponses, AddTagToPostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/posts/slug/{slug}/tags/{tagSlug}',
    ...options
});

/**
 * Get all categories
 */
export const getCategories = <ThrowOnError extends boolean = false>(options?: Options<GetCategoriesData, ThrowOnError>) => (options?.client ?? client).get<GetCategoriesResponses, GetCategoriesErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/categories/',
    ...options
});

/**
 * Create a new category (admin)
 */
export const createCategory = <ThrowOnError extends boolean = false>(options: Options<CreateCategoryData, ThrowOnError>) => (options.client ?? client).post<CreateCategoryResponses, CreateCategoryErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/categories/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a category (admin)
 */
export const deleteCategory = <ThrowOnError extends boolean = false>(options: Options<DeleteCategoryData, ThrowOnError>) => (options.client ?? client).delete<DeleteCategoryResponses, DeleteCategoryErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/categories/{slug}',
    ...options
});

/**
 * Get category by slug
 */
export const getCategoryBySlug = <ThrowOnError extends boolean = false>(options: Options<GetCategoryBySlugData, ThrowOnError>) => (options.client ?? client).get<GetCategoryBySlugResponses, GetCategoryBySlugErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/categories/{slug}',
    ...options
});

/**
 * Update a category (admin)
 */
export const updateCategory = <ThrowOnError extends boolean = false>(options: Options<UpdateCategoryData, ThrowOnError>) => (options.client ?? client).patch<UpdateCategoryResponses, UpdateCategoryErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/categories/{slug}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get all tags
 */
export const getTags = <ThrowOnError extends boolean = false>(options?: Options<GetTagsData, ThrowOnError>) => (options?.client ?? client).get<GetTagsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/tags/',
    ...options
});

/**
 * Create a new tag (admin)
 */
export const createTag = <ThrowOnError extends boolean = false>(options: Options<CreateTagData, ThrowOnError>) => (options.client ?? client).post<CreateTagResponses, CreateTagErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/tags/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a tag (admin)
 */
export const deleteTag = <ThrowOnError extends boolean = false>(options: Options<DeleteTagData, ThrowOnError>) => (options.client ?? client).delete<DeleteTagResponses, DeleteTagErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/tags/{slug}',
    ...options
});

/**
 * Get tag by slug
 */
export const getTagBySlug = <ThrowOnError extends boolean = false>(options: Options<GetTagBySlugData, ThrowOnError>) => (options.client ?? client).get<GetTagBySlugResponses, GetTagBySlugErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/tags/{slug}',
    ...options
});

/**
 * Update a tag (admin)
 */
export const updateTag = <ThrowOnError extends boolean = false>(options: Options<UpdateTagData, ThrowOnError>) => (options.client ?? client).patch<UpdateTagResponses, UpdateTagErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/tags/{slug}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get public user profile
 */
export const getPublicUserById = <ThrowOnError extends boolean = false>(options: Options<GetPublicUserByIdData, ThrowOnError>) => (options.client ?? client).get<GetPublicUserByIdResponses, GetPublicUserByIdErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/users/{userId}',
    ...options
});

/**
 * Get current user profile
 */
export const getMe = <ThrowOnError extends boolean = false>(options?: Options<GetMeData, ThrowOnError>) => (options?.client ?? client).get<GetMeResponses, GetMeErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/users/me',
    ...options
});

/**
 * Update current user profile
 */
export const updateMe = <ThrowOnError extends boolean = false>(options: Options<UpdateMeData, ThrowOnError>) => (options.client ?? client).patch<UpdateMeResponses, UpdateMeErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/users/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update current user password
 */
export const updateMePassword = <ThrowOnError extends boolean = false>(options: Options<UpdateMePasswordData, ThrowOnError>) => (options.client ?? client).patch<UpdateMePasswordResponses, UpdateMePasswordErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/users/me/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get stats for current user
 */
export const getMyStats = <ThrowOnError extends boolean = false>(options?: Options<GetMyStatsData, ThrowOnError>) => (options?.client ?? client).get<GetMyStatsResponses, GetMyStatsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/stats/',
    ...options
});

/**
 * Get activity for current user by period
 */
export const getActivity = <ThrowOnError extends boolean = false>(options: Options<GetActivityData, ThrowOnError>) => (options.client ?? client).get<GetActivityResponses, GetActivityErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/stats/activity/{period}',
    ...options
});
