// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:3001' | (string & {});
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    200: unknown;
};

export type RegisterData = {
    body: {
        email: string;
        password: string;
        displayName: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type RegisterErrors = {
    400: {
        message: string;
    };
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    201: {
        user: {
            id: string;
            email: string;
            displayName: string;
            role: string;
            createdAt: string;
            updatedAt: string;
        };
        token: string;
    };
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LoginData = {
    body: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginErrors = {
    401: {
        message: string;
    };
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    200: {
        user: {
            id: string;
            email: string;
            displayName: string;
            role: string;
            createdAt: string;
            updatedAt: string;
        };
        token: string;
    };
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type GetPostsData = {
    body?: never;
    path?: never;
    query?: {
        page?: string;
        limit?: string;
        search?: string;
        category?: string;
        tag?: string;
        published?: boolean;
    };
    url: '/api/v1/posts/';
};

export type GetPostsResponses = {
    200: {
        data: Array<{
            title: string;
            slug: string;
            content: string;
            excerpt: string;
            published: boolean;
            views: number;
            createdAt: string;
            updatedAt: string;
            author: {
                displayName: string;
                email: string;
            };
            category?: {
                name: string;
                slug: string;
            };
            postTags: Array<{
                tag: {
                    id: string;
                    name: string;
                    slug: string;
                };
            }>;
        }>;
        meta: {
            total: number;
            page: number;
            limit: number;
            totalPages: number;
        };
    };
};

export type GetPostsResponse = GetPostsResponses[keyof GetPostsResponses];

export type CreatePostData = {
    body: {
        title: string;
        content: string;
        excerpt: string;
        published?: boolean;
        categorySlug?: string;
        tagSlugs?: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/api/v1/posts/';
};

export type CreatePostErrors = {
    400: {
        message: string;
    };
};

export type CreatePostError = CreatePostErrors[keyof CreatePostErrors];

export type CreatePostResponses = {
    201: {
        title: string;
        slug: string;
        content: string;
        excerpt: string;
        published: boolean;
        views: number;
        createdAt: string;
        updatedAt: string;
        author: {
            displayName: string;
            email: string;
        };
        category?: {
            name: string;
            slug: string;
        };
        postTags: Array<{
            tag: {
                id: string;
                name: string;
                slug: string;
            };
        }>;
    };
};

export type CreatePostResponse = CreatePostResponses[keyof CreatePostResponses];

export type DeletePostData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/posts/slug/{slug}';
};

export type DeletePostErrors = {
    404: {
        message: string;
    };
};

export type DeletePostError = DeletePostErrors[keyof DeletePostErrors];

export type DeletePostResponses = {
    200: {
        slug: string;
    };
};

export type DeletePostResponse = DeletePostResponses[keyof DeletePostResponses];

export type GetPostBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/posts/slug/{slug}';
};

export type GetPostBySlugErrors = {
    404: {
        message: string;
    };
};

export type GetPostBySlugError = GetPostBySlugErrors[keyof GetPostBySlugErrors];

export type GetPostBySlugResponses = {
    200: {
        title: string;
        slug: string;
        content: string;
        excerpt: string;
        published: boolean;
        views: number;
        createdAt: string;
        updatedAt: string;
        author: {
            displayName: string;
            email: string;
        };
        category?: {
            name: string;
            slug: string;
        };
        postTags: Array<{
            tag: {
                id: string;
                name: string;
                slug: string;
            };
        }>;
    };
};

export type GetPostBySlugResponse = GetPostBySlugResponses[keyof GetPostBySlugResponses];

export type UpdatePostBySlugData = {
    body: {
        title?: string;
        content?: string;
        excerpt?: string;
        published?: boolean;
        categorySlug?: string;
        tagSlugs?: Array<string>;
    };
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/posts/slug/{slug}';
};

export type UpdatePostBySlugErrors = {
    404: {
        message: string;
    };
};

export type UpdatePostBySlugError = UpdatePostBySlugErrors[keyof UpdatePostBySlugErrors];

export type UpdatePostBySlugResponses = {
    200: {
        title: string;
        slug: string;
        content: string;
        excerpt: string;
        published: boolean;
        views: number;
        createdAt: string;
        updatedAt: string;
        author: {
            displayName: string;
            email: string;
        };
        category?: {
            name: string;
            slug: string;
        };
        postTags: Array<{
            tag: {
                id: string;
                name: string;
                slug: string;
            };
        }>;
    };
};

export type UpdatePostBySlugResponse = UpdatePostBySlugResponses[keyof UpdatePostBySlugResponses];

export type RemoveTagFromPostData = {
    body?: never;
    path: {
        slug: string;
        tagSlug: string;
    };
    query?: never;
    url: '/api/v1/posts/slug/{slug}/tags/{tagSlug}';
};

export type RemoveTagFromPostErrors = {
    400: {
        message: string;
    };
    404: {
        message: string;
    };
};

export type RemoveTagFromPostError = RemoveTagFromPostErrors[keyof RemoveTagFromPostErrors];

export type RemoveTagFromPostResponses = {
    200: {
        postSlug: string;
        tagSlug: string;
    };
};

export type RemoveTagFromPostResponse = RemoveTagFromPostResponses[keyof RemoveTagFromPostResponses];

export type AddTagToPostData = {
    body?: never;
    path: {
        slug: string;
        tagSlug: string;
    };
    query?: never;
    url: '/api/v1/posts/slug/{slug}/tags/{tagSlug}';
};

export type AddTagToPostErrors = {
    400: {
        message: string;
    };
    404: {
        message: string;
    };
};

export type AddTagToPostError = AddTagToPostErrors[keyof AddTagToPostErrors];

export type AddTagToPostResponses = {
    200: {
        postSlug: string;
        tagSlug: string;
    };
};

export type AddTagToPostResponse = AddTagToPostResponses[keyof AddTagToPostResponses];

export type GetCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/categories/';
};

export type GetCategoriesErrors = {
    404: {
        message: string;
    };
};

export type GetCategoriesError = GetCategoriesErrors[keyof GetCategoriesErrors];

export type GetCategoriesResponses = {
    200: Array<{
        name: string;
        slug: string;
    }>;
};

export type GetCategoriesResponse = GetCategoriesResponses[keyof GetCategoriesResponses];

export type CreateCategoryData = {
    body: {
        name: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/categories/';
};

export type CreateCategoryErrors = {
    400: {
        message: string;
    };
};

export type CreateCategoryError = CreateCategoryErrors[keyof CreateCategoryErrors];

export type CreateCategoryResponses = {
    201: {
        name: string;
        slug: string;
    };
};

export type CreateCategoryResponse = CreateCategoryResponses[keyof CreateCategoryResponses];

export type DeleteCategoryData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/categories/{slug}';
};

export type DeleteCategoryErrors = {
    400: {
        message: string;
    };
    404: {
        message: string;
    };
};

export type DeleteCategoryError = DeleteCategoryErrors[keyof DeleteCategoryErrors];

export type DeleteCategoryResponses = {
    200: {
        name: string;
        slug: string;
    };
};

export type DeleteCategoryResponse = DeleteCategoryResponses[keyof DeleteCategoryResponses];

export type GetCategoryBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/categories/{slug}';
};

export type GetCategoryBySlugErrors = {
    404: {
        message: string;
    };
};

export type GetCategoryBySlugError = GetCategoryBySlugErrors[keyof GetCategoryBySlugErrors];

export type GetCategoryBySlugResponses = {
    200: {
        name: string;
        slug: string;
    };
};

export type GetCategoryBySlugResponse = GetCategoryBySlugResponses[keyof GetCategoryBySlugResponses];

export type UpdateCategoryData = {
    body: {
        name?: string;
    };
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/categories/{slug}';
};

export type UpdateCategoryErrors = {
    400: {
        message: string;
    };
    404: {
        message: string;
    };
};

export type UpdateCategoryError = UpdateCategoryErrors[keyof UpdateCategoryErrors];

export type UpdateCategoryResponses = {
    200: {
        name: string;
        slug: string;
    };
};

export type UpdateCategoryResponse = UpdateCategoryResponses[keyof UpdateCategoryResponses];

export type GetTagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tags/';
};

export type GetTagsResponses = {
    200: Array<{
        name: string;
        slug: string;
    }>;
};

export type GetTagsResponse = GetTagsResponses[keyof GetTagsResponses];

export type CreateTagData = {
    body: {
        name: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/tags/';
};

export type CreateTagErrors = {
    400: {
        message: string;
    };
};

export type CreateTagError = CreateTagErrors[keyof CreateTagErrors];

export type CreateTagResponses = {
    201: {
        name: string;
        slug: string;
    };
};

export type CreateTagResponse = CreateTagResponses[keyof CreateTagResponses];

export type DeleteTagData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/tags/{slug}';
};

export type DeleteTagErrors = {
    400: {
        message: string;
    };
    404: {
        message: string;
    };
};

export type DeleteTagError = DeleteTagErrors[keyof DeleteTagErrors];

export type DeleteTagResponses = {
    200: {
        name: string;
        slug: string;
    };
};

export type DeleteTagResponse = DeleteTagResponses[keyof DeleteTagResponses];

export type GetTagBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/tags/{slug}';
};

export type GetTagBySlugErrors = {
    404: {
        message: string;
    };
};

export type GetTagBySlugError = GetTagBySlugErrors[keyof GetTagBySlugErrors];

export type GetTagBySlugResponses = {
    200: {
        name: string;
        slug: string;
    };
};

export type GetTagBySlugResponse = GetTagBySlugResponses[keyof GetTagBySlugResponses];

export type UpdateTagData = {
    body: {
        name?: string;
    };
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/tags/{slug}';
};

export type UpdateTagErrors = {
    400: {
        message: string;
    };
    404: {
        message: string;
    };
};

export type UpdateTagError = UpdateTagErrors[keyof UpdateTagErrors];

export type UpdateTagResponses = {
    200: {
        name: string;
        slug: string;
    };
};

export type UpdateTagResponse = UpdateTagResponses[keyof UpdateTagResponses];

export type GetPublicUserByIdData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/v1/users/{userId}';
};

export type GetPublicUserByIdErrors = {
    404: {
        message: string;
    };
};

export type GetPublicUserByIdError = GetPublicUserByIdErrors[keyof GetPublicUserByIdErrors];

export type GetPublicUserByIdResponses = {
    200: {
        username: string;
        displayName: string;
        createdAt: string;
    };
};

export type GetPublicUserByIdResponse = GetPublicUserByIdResponses[keyof GetPublicUserByIdResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type GetMeErrors = {
    404: {
        message: string;
    };
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    200: {
        username: string;
        displayName: string;
        createdAt: string;
        email: string;
        role: string;
    };
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type UpdateMeData = {
    body: {
        displayName?: string;
        username?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UpdateMeErrors = {
    400: {
        message: string;
    };
};

export type UpdateMeError = UpdateMeErrors[keyof UpdateMeErrors];

export type UpdateMeResponses = {
    200: {
        username: string;
        displayName: string;
        createdAt: string;
        email: string;
        role: string;
    };
};

export type UpdateMeResponse = UpdateMeResponses[keyof UpdateMeResponses];

export type UpdateMePasswordData = {
    body: {
        currentPassword: string;
        newPassword: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UpdateMePasswordErrors = {
    400: {
        message: string;
    };
};

export type UpdateMePasswordError = UpdateMePasswordErrors[keyof UpdateMePasswordErrors];

export type UpdateMePasswordResponses = {
    200: {
        username: string;
        displayName: string;
        createdAt: string;
        email: string;
        role: string;
    };
};

export type UpdateMePasswordResponse = UpdateMePasswordResponses[keyof UpdateMePasswordResponses];

export type GetMyStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/stats/';
};

export type GetMyStatsErrors = {
    400: {
        message: string;
    };
};

export type GetMyStatsError = GetMyStatsErrors[keyof GetMyStatsErrors];

export type GetMyStatsResponses = {
    200: {
        totalPosts: number;
        totalPublishedPosts: number;
        totalDraftPosts: number;
        totalViews: number;
        totalComments: number;
        totalLikes: number;
        postsByMonth: Array<{
            month: string;
            count: number;
        }>;
    };
};

export type GetMyStatsResponse = GetMyStatsResponses[keyof GetMyStatsResponses];
