// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:3001' | (string & {});
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    200: unknown;
};

export type PostApiV1AuthRegisterData = {
    body: {
        email: string;
        password: string;
        displayName: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type PostApiV1AuthRegisterResponses = {
    200: unknown;
};

export type PostApiV1AuthLoginData = {
    body: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type PostApiV1AuthLoginResponses = {
    200: unknown;
};

export type GetApiV1PostsData = {
    body?: never;
    path?: never;
    query?: {
        page?: string;
        limit?: string;
        search?: string;
        category?: string;
        tag?: string;
        published?: string;
    };
    url: '/api/v1/posts/';
};

export type GetApiV1PostsResponses = {
    200: unknown;
};

export type PostApiV1PostsData = {
    body: {
        title: string;
        content: string;
        excerpt: string;
        published?: boolean;
        categoryId?: string | unknown | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/posts/';
};

export type PostApiV1PostsResponses = {
    200: unknown;
};

export type DeleteApiV1PostsSlugBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/posts/slug/{slug}';
};

export type DeleteApiV1PostsSlugBySlugResponses = {
    200: unknown;
};

export type GetApiV1PostsSlugBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/posts/slug/{slug}';
};

export type GetApiV1PostsSlugBySlugResponses = {
    200: unknown;
};

export type PatchApiV1PostsSlugBySlugData = {
    body: {
        title?: string;
        slug?: string;
        content?: string;
        excerpt?: string;
        published?: boolean;
        categoryId?: string | unknown | null;
    };
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/posts/slug/{slug}';
};

export type PatchApiV1PostsSlugBySlugResponses = {
    200: unknown;
};

export type DeleteApiV1PostsSlugBySlugTagsByTagSlugData = {
    body?: never;
    path: {
        slug: string;
        tagSlug: string;
    };
    query?: never;
    url: '/api/v1/posts/slug/{slug}/tags/{tagSlug}';
};

export type DeleteApiV1PostsSlugBySlugTagsByTagSlugResponses = {
    200: unknown;
};

export type PutApiV1PostsSlugBySlugTagsByTagSlugData = {
    body?: never;
    path: {
        slug: string;
        tagSlug: string;
    };
    query?: never;
    url: '/api/v1/posts/slug/{slug}/tags/{tagSlug}';
};

export type PutApiV1PostsSlugBySlugTagsByTagSlugResponses = {
    200: unknown;
};

export type GetApiV1CategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/categories/';
};

export type GetApiV1CategoriesResponses = {
    200: unknown;
};

export type PostApiV1CategoriesData = {
    body: {
        name: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/categories/';
};

export type PostApiV1CategoriesResponses = {
    200: unknown;
};

export type DeleteApiV1CategoriesBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/categories/{slug}';
};

export type DeleteApiV1CategoriesBySlugResponses = {
    200: unknown;
};

export type GetApiV1CategoriesBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/categories/{slug}';
};

export type GetApiV1CategoriesBySlugResponses = {
    200: unknown;
};

export type PatchApiV1CategoriesBySlugData = {
    body: {
        name?: string;
    };
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/categories/{slug}';
};

export type PatchApiV1CategoriesBySlugResponses = {
    200: unknown;
};

export type GetApiV1TagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tags/';
};

export type GetApiV1TagsResponses = {
    200: unknown;
};

export type PostApiV1TagsData = {
    body: {
        name: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/tags/';
};

export type PostApiV1TagsResponses = {
    200: unknown;
};

export type DeleteApiV1TagsBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/tags/{slug}';
};

export type DeleteApiV1TagsBySlugResponses = {
    200: unknown;
};

export type GetApiV1TagsBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/tags/{slug}';
};

export type GetApiV1TagsBySlugResponses = {
    200: unknown;
};

export type PatchApiV1TagsBySlugData = {
    body: {
        name?: string;
    };
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/tags/{slug}';
};

export type PatchApiV1TagsBySlugResponses = {
    200: unknown;
};

export type GetApiV1UsersByUserIdData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/v1/users/{userId}';
};

export type GetApiV1UsersByUserIdResponses = {
    200: unknown;
};

export type GetApiV1UsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type GetApiV1UsersMeResponses = {
    200: unknown;
};

export type PatchApiV1UsersMeData = {
    body: {
        displayName?: string;
        username?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type PatchApiV1UsersMeResponses = {
    200: unknown;
};

export type PatchApiV1UsersMePasswordData = {
    body: {
        currentPassword: string;
        newPassword: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type PatchApiV1UsersMePasswordResponses = {
    200: unknown;
};

export type GetApiV1StatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/stats/';
};

export type GetApiV1StatsResponses = {
    200: unknown;
};
