// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { createPost, deletePost, getPostBySlug, getPosts, login, type Options, register, updatePostBySlug } from '../sdk.gen';
import type { CreatePostData, CreatePostError, CreatePostResponse, DeletePostData, DeletePostResponse, GetPostBySlugData, GetPostBySlugError, GetPostBySlugResponse, GetPostsData, GetPostsResponse, LoginData, LoginError, LoginResponse, RegisterData, RegisterError, RegisterResponse, UpdatePostBySlugData, UpdatePostBySlugError, UpdatePostBySlugResponse } from '../types.gen';

/**
 * Delete a post
 *
 * Deletes a blog post by its slug. Only an admin can delete a post.
 */
export const deletePostMutation = (options?: Partial<Options<DeletePostData>>): UseMutationOptions<DeletePostResponse, AxiosError<DefaultError>, Options<DeletePostData>> => {
    const mutationOptions: UseMutationOptions<DeletePostResponse, AxiosError<DefaultError>, Options<DeletePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deletePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getPostBySlugQueryKey = (options: Options<GetPostBySlugData>) => createQueryKey('getPostBySlug', options);

/**
 * Get post by slug
 *
 * Retrieves a single blog post by its slug. The slug is a URL-friendly identifier for the post, typically derived from the post's title. For example, a post titled 'My First Post' might have a slug of 'my-first-post'.
 */
export const getPostBySlugOptions = (options: Options<GetPostBySlugData>) => queryOptions<GetPostBySlugResponse, AxiosError<GetPostBySlugError>, GetPostBySlugResponse, ReturnType<typeof getPostBySlugQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPostBySlug({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPostBySlugQueryKey(options)
});

/**
 * Update an existing post by slug
 *
 * Updates an existing blog post using the slug. The request body can include the title, content, and published status of the post. Only the author of the post or an admin can update the post.
 */
export const updatePostBySlugMutation = (options?: Partial<Options<UpdatePostBySlugData>>): UseMutationOptions<UpdatePostBySlugResponse, AxiosError<UpdatePostBySlugError>, Options<UpdatePostBySlugData>> => {
    const mutationOptions: UseMutationOptions<UpdatePostBySlugResponse, AxiosError<UpdatePostBySlugError>, Options<UpdatePostBySlugData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updatePostBySlug({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getPostsQueryKey = (options?: Options<GetPostsData>) => createQueryKey('getPosts', options);

/**
 * Get all posts
 *
 * Retrieves a list of all blog posts. Optionally, you can filter to only include published posts by setting the 'publishedOnly' query parameter to true.
 */
export const getPostsOptions = (options?: Options<GetPostsData>) => queryOptions<GetPostsResponse, AxiosError<DefaultError>, GetPostsResponse, ReturnType<typeof getPostsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPosts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPostsQueryKey(options)
});

/**
 * Create a new post
 *
 * Creates a new blog post. The request body should include the title, content, and optionally the published status of the post. The authenticated user will be set as the author of the post.
 */
export const createPostMutation = (options?: Partial<Options<CreatePostData>>): UseMutationOptions<CreatePostResponse, AxiosError<CreatePostError>, Options<CreatePostData>> => {
    const mutationOptions: UseMutationOptions<CreatePostResponse, AxiosError<CreatePostError>, Options<CreatePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Register a new user
 *
 * Registers a new user with the provided username, email, and password. Returns an authentication response containing a JWT token upon successful registration.
 */
export const registerMutation = (options?: Partial<Options<RegisterData>>): UseMutationOptions<RegisterResponse, AxiosError<RegisterError>, Options<RegisterData>> => {
    const mutationOptions: UseMutationOptions<RegisterResponse, AxiosError<RegisterError>, Options<RegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await register({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Login a user
 *
 * Authenticates a user with the provided username and password. Returns an authentication response containing a JWT token upon successful login.
 */
export const loginMutation = (options?: Partial<Options<LoginData>>): UseMutationOptions<LoginResponse, AxiosError<LoginError>, Options<LoginData>> => {
    const mutationOptions: UseMutationOptions<LoginResponse, AxiosError<LoginError>, Options<LoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await login({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
