// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080/api/v1' | (string & {});
};

export type UpdatePostRequest = {
    title?: string;
    content?: string;
    excerpt?: string;
    published?: boolean;
};

export type PostResponse = {
    title: string;
    slug: string;
    content: string;
    excerpt: string;
    published: boolean;
    createdAt: string;
    updatedAt: string;
};

export type CreatePostRequest = {
    title: string;
    content: string;
    excerpt: string;
    published: boolean;
};

export type RegisterRequest = {
    email: string;
    password: string;
    displayName: string;
};

export type AuthResponse = {
    token: string;
    email: string;
    displayName: string;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type DeletePostData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/posts/{id}';
};

export type DeletePostErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Post not found
     */
    404: unknown;
};

export type DeletePostResponses = {
    /**
     * Post deleted successfully
     */
    204: void;
};

export type DeletePostResponse = DeletePostResponses[keyof DeletePostResponses];

export type UpdatePostData = {
    body: UpdatePostRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/posts/{id}';
};

export type UpdatePostErrors = {
    /**
     * Invalid request data
     */
    400: PostResponse;
    /**
     * Unauthorized
     */
    401: PostResponse;
};

export type UpdatePostError = UpdatePostErrors[keyof UpdatePostErrors];

export type UpdatePostResponses = {
    /**
     * OK
     */
    200: PostResponse;
};

export type UpdatePostResponse = UpdatePostResponses[keyof UpdatePostResponses];

export type GetPostsData = {
    body?: never;
    path?: never;
    query?: {
        publishedOnly?: boolean;
    };
    url: '/posts';
};

export type GetPostsResponses = {
    /**
     * OK
     */
    200: Array<PostResponse>;
};

export type GetPostsResponse = GetPostsResponses[keyof GetPostsResponses];

export type CreatePostData = {
    body: CreatePostRequest;
    headers: {
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/posts';
};

export type CreatePostErrors = {
    /**
     * Invalid request data
     */
    400: PostResponse;
    /**
     * Unauthorized
     */
    401: PostResponse;
};

export type CreatePostError = CreatePostErrors[keyof CreatePostErrors];

export type CreatePostResponses = {
    /**
     * OK
     */
    201: PostResponse;
};

export type CreatePostResponse = CreatePostResponses[keyof CreatePostResponses];

export type RegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterErrors = {
    /**
     * Invalid registration request
     */
    400: AuthResponse;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * User registered successfully
     */
    201: AuthResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * Invalid login request
     */
    400: AuthResponse;
    /**
     * Invalid username or password
     */
    401: AuthResponse;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * User logged in successfully
     */
    200: AuthResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type GetPostBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/posts/{slug}';
};

export type GetPostBySlugErrors = {
    /**
     * Post not found
     */
    404: PostResponse;
};

export type GetPostBySlugError = GetPostBySlugErrors[keyof GetPostBySlugErrors];

export type GetPostBySlugResponses = {
    /**
     * OK
     */
    200: PostResponse;
};

export type GetPostBySlugResponse = GetPostBySlugResponses[keyof GetPostBySlugResponses];
